server:
  port: 8080

api:
  busan:
    base-url: http://apis.data.go.kr/6260000/
  seoul:
    base-url: http://openapi.seoul.go.kr:8088/

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml